[WIP] CI
Immobylette/immobylette--app-mobile pull request #12
Opened 2024-05-07 14:00 UTC by patacoing

2024-05-07 17:18 UTC, patacoing commented
![](https://github.trello.services/images/mini-trello-icon.png) [CI/CD sur l'application Mobile](https://trello.com/c/jDnRlr8j/60-ci-cd-sur-lapplication-mobile)

2024-05-08 18:46 UTC, OdakK requested changes

2024-05-08 18:46 UTC, OdakK commented on .github/workflows/gradle.yml
> +          prefix=$(echo "${{ github.event.head_commit.message }}" | cut -d'/' -f 1)")
les commits sont au format feat:.... donc il faut cut avec le délimiteur : et non /

2024-05-08 18:46 UTC, OdakK commented on .github/workflows/gradle.yml
> +      - name: Extract source branch name
Plus besoin de ce step

2024-05-09 19:54 UTC, patacoing commented on .github/workflows/gradle.yml
> +          prefix=$(echo "${{ github.event.head_commit.message }}" | cut -d'/' -f 1)")
bah non, on aait dit que on mettait le nom de la branche

2024-05-10 14:27 UTC, LfrPaul approved these changes

2024-05-12 14:08 UTC, merged