[ADD] confirmation page
Immobylette/immobylette--app-mobile pull request #13
Opened 2024-05-10 13:52 UTC by patacoing

Modification du sharedViewModel currentProperty pour stocker toute la property au lieu de seulement l'id ==> on a accès au currentTenant qui doit être affiché dans la page de confirmation.

2024-05-10 13:53 UTC, patacoing commented
![](https://github.trello.services/images/mini-trello-icon.png) [Page de confirmation de présence](https://trello.com/c/qx4jAepu/73-page-de-confirmation-de-pr%C3%A9sence)

2024-05-10 14:40 UTC, LfrPaul approved these changes

2024-05-11 23:56 UTC, LfrPaul requested changes
Je viens de me rendre compte, au moment de startInventory il faudrait stocker l'UUID retourné dans un CurrentInventoryViewModel puisqu'on en aura besoin pour toutes les requêtes des autres pages

2024-05-13 13:59 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/inventory/current/CurrentInventoryViewModel.kt
> +    fun startInventory(propertyId: UUID, agentId: UUID) {
ça serait pas mieux de quand même laisser cette méthode dans ConfirmationViewModel (vu que c'est spécifique à la page de confirmation)
Et d'ajouter une méthode setCurrentInventory dans le CurrentInventoryViewModel qu'on vient appeler dans ConfirmationPage une fois qu'on a récup l'UUID de l'état des lieux créé ?

2024-05-13 14:08 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/inventory/current/CurrentInventoryViewModel.kt
> +    fun startInventory(propertyId: UUID, agentId: UUID) {
je vais essayer de voir, c'est parce que je voyais pas trop comment faire pour attendre la réponse de l'api (et donc attendre la méthode startInventory qui doit me renvoyer l'id)

2024-05-13 14:18 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/inventory/current/CurrentInventoryViewModel.kt
> +    fun startInventory(propertyId: UUID, agentId: UUID) {
mmh bonne question, en soit est-ce qu'on a besoin de garder le viewModelScope.launch ici ? On pourrait pas faire une fonction qui retourne un UUID ?

2024-05-13 16:29 UTC, patacoing commented
Bon j'ai regardé sur internet et je voyais pas trop comment faire pour avec une fonction asynchrone et récup la data dans le composable (car on ne passe pas en param le viewModel) ducoup je passe une callback à la fonction startInventory pour pouvoir stocker l'id du currentInventory après la fin de la requête

2024-05-13 16:32 UTC, LfrPaul approved these changes

2024-05-13 18:15 UTC, OdakK approved these changes

2024-05-13 20:18 UTC, merged