[ADD] GoToRoom Page
Immobylette/immobylette--app-mobile pull request #15
Opened 2024-05-13 22:10 UTC by LfrPaul

- GoToRoom
- RoomDto
- RoomService

CurrentRoomViewModel -> Seulement un INT pour afficher en bas de page "Pièces vérifiées X/Y"

Pour l'affichage de chaque propriété j'ai fait un composant PropertyRow, qui affichera le nom de la propriété en gras, puis un contenu libre

2024-05-13 22:10 UTC, LfrPaul commented
![](https://github.trello.services/images/mini-trello-icon.png) [Page Aller dans la pièce](https://trello.com/c/l8H6rhWC/74-page-aller-dans-la-pi%C3%A8ce)

2024-05-14 11:07 UTC, patacoing requested changes

2024-05-14 11:07 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/room/gotoroom/GoToRoomPage.kt
> +                            Text(text = state.description,fontWeight = FontWeight.Bold)
la description en gras dans la maquette est un oubli, mettre en normal

2024-05-14 11:07 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/room/gotoroom/GoToRoomPage.kt
> +                            BlueRectangleWithText(text = state.roomType)
le roomType peut être null

2024-05-14 11:07 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/data/dto/RoomDto.kt
> +    val roomType: String,
peut être null

2024-05-14 11:07 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/room/gotoroom/RoomState.kt
> +    val roomType: String = "",
peut être null

2024-05-14 11:07 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/room/gotoroom/GoToRoomViewModel.kt
> +            }
log l'erreur avec Log.e si la requête n'est pas successful

2024-05-14 23:14 UTC, patacoing approved these changes

2024-05-17 16:31 UTC, merged