[ADD] PhotoDetail composable
Immobylette/immobylette--app-mobile pull request #17
Opened 2024-05-13 22:56 UTC by patacoing

2024-05-13 22:57 UTC, patacoing commented
![](https://github.trello.services/images/mini-trello-icon.png) [Composant détail photo](https://trello.com/c/9j3S00E5/81-composant-d%C3%A9tail-photo)

2024-05-14 15:28 UTC, LfrPaul requested changes

2024-05-14 15:28 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/PhotoDetail.kt
> +                    modifier = modifier.width(150.dp)
il faudrait pas mettre un nouveau Modifier plutôt que d'utiliser le modifier passé en argument partout dans le composant ?

2024-05-14 23:12 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/PhotoDetail.kt
> +                    modifier = modifier.width(150.dp)
Si, ok mais à quel moment on doit l'utiliser la param modifier du composable ? parce que si je ne l'utilise pas dans le composable, si je l'applique au composable a n'a pas d'effet si ?

par exemple : 

PhotoDetail(modifier = Modifier.width(...))

2024-05-15 14:22 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/PhotoDetail.kt
> +                    modifier = modifier.width(150.dp)
perso je le mets sur le premier élément du composant donc ici le premier Box mais pas autre part

2024-05-16 14:52 UTC, LfrPaul approved these changes

2024-05-17 11:15 UTC, merged