Feat/imb 76
Immobylette/immobylette--app-mobile pull request #19
Opened 2024-05-14 23:06 UTC by patacoing

- j'ai du modifié le composant Tip lorsque l'on utilise la typography labelSmall parce que sinon çça fesait pas un cercle
- les photos dans base photos et du précédent état des lieux ne contiennent pas de description
- si un élément est checked ou bien en erreur => un clic dessus ne provoque pas l'agrandissement de la card

[
![image](https://github.com/Immobylette/immobylette--app-mobile/assets/78411800/3c5dbe16-1fbd-48ae-8898-a9c26eed97c5)
](url)

2024-05-14 23:06 UTC, patacoing commented
![](https://github.trello.services/images/mini-trello-icon.png) [Composant élément](https://trello.com/c/BuZvQNLM/76-composant-%C3%A9l%C3%A9ment)

2024-05-15 15:10 UTC, LfrPaul requested changes

2024-05-15 15:10 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Tip.kt
> +    }
ça serait pas mieux de mettre juste une valeur par défaut (comme c'était avant) et de laisser la liberté au composant parent de changer la width et le padding en mettant un modifier (et donc de laisser éventuellement le composant parent faire ce calcul)

2024-05-15 15:10 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Element.kt
> +enum class ElementState(val label: String = "") {
déplacer dans un fichier à part puisqu'on en aura besoin dans d'autres composants/pages (data > enum ?)

2024-05-15 15:10 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Element.kt
> +            .clip(RoundedCornerShape(10.dp)),
Il y a pas moyen d'utiliser un "AnimatedVisibility" comme pour le composant PropertyCard pour éviter de devoir fixer deux tailles comme ça ?

2024-05-15 19:36 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Element.kt
> +            .clip(RoundedCornerShape(10.dp)),
le truc c'est que AnimatedVisibility va rendre visible le rest quand on déploie alors que l'objectif c'est d'avoir une Box dont la hauteur augmente en animation

2024-05-15 21:36 UTC, LfrPaul approved these changes

2024-05-17 11:11 UTC, merged