Composant Agent
Immobylette/immobylette--app-mobile pull request #2
Opened 2024-04-09 14:43 UTC by patacoing

- Ajout d'une dépendance pour récupérer les images où on a l'url
- Ajout de la permission internet pour les images
- Ajout de la font "Inter" pour le nom de l'agent

2024-04-09 14:44 UTC, patacoing commented
![](https://github.trello.services/images/mini-trello-icon.png) [Composant Agent](https://trello.com/c/FMEiX8X9/53-composant-agent)

2024-04-09 14:47 UTC, OdakK commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Agent.kt
> +            URL("https://static.cotemaison.fr/medias_10824/w_2048,h_1146,c_crop,x_0,y_184/w_640,h_360,c_fill,g_north/v1456392403/10-conseils-pour-rendre-votre-chien-heureux_5542245.jpg"),
Faire un fichier avec les constantes des previews ? (URL et strings)

2024-04-09 14:52 UTC, OdakK approved these changes

2024-04-09 15:20 UTC, LfrPaul approved these changes

2024-04-09 19:26 UTC, AlexisPop commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Agent.kt
> +            .height(140.dp)
Placer ces valeurs dans Theme.CompositionLocalProvider

2024-04-09 19:26 UTC, AlexisPop commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Agent.kt
> +    name: String,
Ajouter des valeurs par défaut ?

2024-04-09 20:34 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Agent.kt
> +            .height(140.dp)
pourquoi ? c'est seulement spécifique à ce composant

2024-04-09 20:34 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Agent.kt
> +    name: String,
On est forcément censé avoir des données à lui passer

2024-04-13 15:07 UTC, AlexisPop commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Agent.kt
> +            .height(140.dp)
Oui mais ça fait partie des constantes propres à notre thème personnalisé, peu importe que ça soit utilisé dans un ou plusieurs composants. C'est préférable de centraliser les constantes de notres thème dans un seul fichier Theme.CompositionLocalProvider. 
Même si une contante est utilisée dans un seul fichier, c'est une bonne pratique de la placer au même endroit que l'ensemble des constantes de l'application qui sont elles peut-être utilisées plusieurs fois.

2024-04-13 15:19 UTC, AlexisPop commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Agent.kt
> +            .height(140.dp)
Réponse ChatGpt : 
Si la largeur du bouton est utilisée de manière cohérente à travers toute votre application ou nécessite de la flexibilité pour s'adapter à différents thèmes ou configurations, il est préférable de la placer dans Theme.kt. Cela facilite la gestion du design à un niveau global et centralise la configuration des styles.

Si la largeur est spécifique à un seul type de bouton ou n'est pas susceptible d'être réutilisée, la définir directement dans Button.kt pourrait être plus simple et plus direct.

Cela dépend vraiment de la manière dont vous souhaitez gérer les styles dans votre application et de l'étendue de la réutilisabilité nécessaire pour vos composants de l'interface utilisateur.

On refait un vote ?

2024-04-13 15:21 UTC, AlexisPop requested changes
Placer les constantes propres au thème dans Theme.kt

2024-04-14 20:55 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Agent.kt
> +            .height(140.dp)
bah ducoup la valeur va être utilisé que dans le composant elle est spécifique à celui-ci

2024-04-18 21:27 UTC, merged