[ADD] walls page
Immobylette/immobylette--app-mobile pull request #27
Opened 2024-05-18 13:39 UTC by patacoing

J'ai essayé de faire une page globale pour les éléments et murs pour que l'on puisse l'utiliser dans la page des éléments

- J'ai fait un WallsViewModel pour les fonctions propres aux walls. Je me dis que des fonctions comme fetchElements auraient du être dans un code global à WallsViewModel et ElementsViewModel sauf que j'aoue que je saait pas trop comment faire donc le code sera dupliqué

- J'ai modifié le composant Button pour ajouter un param permettant de modifier le style du texte (à partir de la typography du thème). Et d'ailleurs j'ai rajouter le modifier .height(IntrinsicSize.Min) car avant j'avais toujours un petit espace blanc

- Fix d'un bug pour la récupération du nombre de rooms d'une propriété

- Modification du CurrentRoomViewModel pour avoir un RoomState plutôt que seulement l'id afin d'avoir toutes les données de la pièce pour les afficher

- Modification du composant Element pour qu'il prenne non pas des listes d'URL mais de PhotoDto (comprenant l'url + la description)

- Ajout dans le fichier de Theme, une background color, avant on était toujours en blanc, là j'ai mis la vraie valeur (gris)

- Dans WallsViewModel je n'ai pas implémenter la fonction permettant de checker tout les éléments car cela fait appel à une route back qui n'est pas encore dev

### Résultats : 

![image](https://github.com/Immobylette/immobylette--app-mobile/assets/78411800/da5b3bfc-ac79-436a-a379-46ae95b94fc4)

![image](https://github.com/Immobylette/immobylette--app-mobile/assets/78411800/8646e950-3a58-43f6-96fc-fe40b7acc170)

![image](https://github.com/Immobylette/immobylette--app-mobile/assets/78411800/672f7182-2ff8-4496-a99b-0b0c4f5f627b)

j'ai la flemme d'ajouter la preview de detail d'une photo mais faite moi confiance ça marche bien, sinon testez vous même

2024-05-18 13:40 UTC, patacoing commented
![](https://github.trello.services/images/mini-trello-icon.png) [Page walls](https://trello.com/c/9PoY3fNs/79-page-walls)

2024-05-18 14:50 UTC, LfrPaul requested changes

2024-05-18 14:50 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/room/elements/ElementMapper.kt
> +    name = "Test1",
changer pour name

2024-05-18 14:50 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/room/elements/ElementMapper.kt
> +    name = "Test1",
changer pour name aussi

2024-05-18 14:50 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/room/elements/WallsViewModel.kt
> +    }
c'est à ce moment qu'on fait la requête 
POST /api/v1/inventories/{id}/elements/{id}

2024-05-18 14:50 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/room/elements/WallsViewModel.kt
> +        //TODO: implement when we'll have the element state page
pourquoi on peut pas la faire maintenant ?

2024-05-18 16:33 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/room/elements/WallsViewModel.kt
> +    }
Ah bon ? Je croyais faire tout les requêtes au moment où on appuyés sur "suivant" dans la page des elements

2024-05-18 16:33 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/room/elements/WallsViewModel.kt
> +        //TODO: implement when we'll have the element state page
La feature côté Back n'est pas encore faite

2024-05-18 16:39 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/room/elements/WallsViewModel.kt
> +    }
bah on avait pas dit que ça allait faire trop lourd (surtout au niveau de l'upload des photos) et qu'on faisait donc un par un ? C'est même pour ça qu'on a fait une requête unique au lieu de faire une requête globale il me semble

2024-05-18 16:47 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/room/elements/WallsViewModel.kt
> +    }
aussi pour reprendre un état des lieux en cours comme ça on gardait une précision du l'avancement au niveau des éléments et pas seulement au niveau d'une pièce

2024-05-19 10:34 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/room/elements/WallsViewModel.kt
> +    }
ah bah oui jsuis bête

2024-05-19 13:42 UTC, LfrPaul approved these changes

2024-05-19 18:05 UTC, AlexisPop approved these changes

2024-05-20 11:17 UTC, merged