[ADD] button composable
Immobylette/immobylette--app-mobile pull request #3
Opened 2024-04-09 19:36 UTC by AlexisPop

Ajout du composable button : 

- Le composable en lui même 
- Les constantes propres au thème de notre application (largeur du bouton)
- Tests de 2 boutons dans MainActivity

2024-04-09 19:39 UTC, AlexisPop commented
![](https://github.trello.services/images/mini-trello-icon.png) [Composant Button](https://trello.com/c/uq1lG64i/58-composant-button)

2024-04-09 20:30 UTC, patacoing requested changes

2024-04-09 20:30 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +fun AppButton(
le composant doit s'appeler Button

2024-04-09 20:30 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +    textButton: String = "Suivant",
mettre text tout court

2024-04-09 20:30 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +    IsOnLeftSide: Boolean = true,
pas de maj sur la première lettre

2024-04-09 20:30 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +    onClickCb: () -> Unit
onClick pour être pareil que les autre composant ayant ce param

2024-04-09 20:30 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +        onClick = {
onClick = onClick

2024-04-09 20:30 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +fun exempleCallback(){
pas besoin d'une callback à part, la mettre directement dans onClickCb = {println(...)}

2024-04-09 20:30 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/theme/Theme.kt
> +private val BorderRavus = 200.dp
as-tu testé si 200.dp en border radius n'était pas trop ?

2024-04-09 20:30 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +                    topEnd = 20.dp
il faut utiliser la constante que tu as définie

2024-04-09 20:30 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFF4081)),
utiliser MaterialTheme.colorScheme.primary

2024-04-09 20:30 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +            text = textButton
tu n'as pas utiliser la police du thème et il faut que le texte soit plus grand

2024-04-09 20:30 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +                RoundedCornerShape(
autant mettre sur la même ligne, tu n'as qu'un param

2024-04-09 20:30 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +            if(modifier == Modifier){
pourquoi ce if ?

2024-04-09 20:32 UTC, patacoing commented
D'ailleurs il faudrait avoir d'autres param pour gérer l'orientation car si on regarde l'affichage de nos boutons on en a plus que 2

2024-04-09 20:48 UTC, AlexisPop commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +fun AppButton(
Le composant Button est un élément standard en Kotlin, on risque de confondre ? En sachant que Button de notre application utiliserait Button de Jetpack Compose ?

2024-04-09 21:05 UTC, AlexisPop commented
> D'ailleurs il faudrait avoir d'autres param pour gérer l'orientation car si on regarde l'affichage de nos boutons on en a plus que 2

C'est quoi les autres orientations possibles pour toi ?

2024-04-09 21:07 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +fun AppButton(
On ne va dans l'app utilisait que notre composant Button

2024-04-09 21:09 UTC, patacoing commented
![image](https://github.com/Immobylette/immobylette--app-mobile/assets/78411800/b11ca3b6-0768-4484-9289-f60cd86420af)

les 2 autres possibilités

2024-04-09 21:10 UTC, AlexisPop commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +fun AppButton(
> On ne va dans l'app utilisait que notre composant Button

Ca va créer de la confusion pour rien ? ex : dans une page on ajoute un bouton, en faisant l'import et aura la possibilité d'ajouter l import android ou celui de notre appli.

2024-04-09 21:11 UTC, AlexisPop commented
> ![image](https://private-user-images.githubusercontent.com/78411800/321003032-b11ca3b6-0768-4484-9289-f60cd86420af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTcyNjAsIm5iZiI6MTcxMjY5Njk2MCwicGF0aCI6Ii83ODQxMTgwMC8zMjEwMDMwMzItYjExY2EzYjYtMDc2OC00NDg0LTkyODktZjYwY2Q4NjQyMGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDIxMDkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ZDcwZGU1MjQ0MDdiMTE1MWNhMzYyNmMyOWQ3ZTExNWE4MTVlYmQzMWM5NjA5M2Y0ZWQzNDE2MmI5ODA5MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V3_4z9lPBsRHp30BvXka9iMWMxb7OI9y8YhG1d4u_RU)
> 
> les 2 autres possibilités

Gauche ou droite ? C'est deja développé

2024-04-09 22:31 UTC, patacoing commented
Non, les 2 ne sont pas fait, tu n'as qu'à chaque fois un coin qui est en border radius, là il y en a 2

2024-04-09 22:33 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +fun AppButton(
Bah faudra juste choisir quoi, parce que sinon on aura que ce composant la qui s'appellera AppButton alors que tous les autres s'appellent Agent, Title, ...

2024-04-09 22:36 UTC, patacoing requested changes

2024-04-09 22:36 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +fun ExempleCallback(){
pas besoin de mettre une callback à l'extérieur de la preview

2024-04-09 22:36 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/theme/Theme.kt
> +val LocalBorderRadius = compositionLocalOf { 0.dp }
N'y a t il pas un autre moyen pour donner ces variables aux composants ? parce que sinon plus on va en avoir plus ça va être horrible à tous passer en param

2024-04-10 06:37 UTC, AlexisPop commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Button.kt
> +fun AppButton(
Oui mais Agent c'est pas un composant classique de Jetpack Compose contrairement à Button

2024-04-10 06:46 UTC, AlexisPop commented
> Non, les 2 ne sont pas fait, tu n'as qu'à chaque fois un coin qui est en border radius, là il y en a 2

L'autre border radius devrait venir du composant père plutôt ? Par exemple dans le composant Pop-up quand on clique sur les détails d'une photo, c'est la Pop-up qui a des borderRadius et arrondie le coin extérieur du bouton, pas le bouton lui même. Pareil pour la page principale.

2024-04-11 07:33 UTC, OdakK commented on app/src/main/java/com/immobylette/appmobile/ui/shared/theme/Theme.kt
> +        LocalAppButtonWidth provides appButtonWidth,
Jamais utilisé ?

2024-04-13 14:39 UTC, AlexisPop commented
> Non, les 2 ne sont pas fait, tu n'as qu'à chaque fois un coin qui est en border radius, là il y en a 2

Le 2e coin pourrait être géré par le composable parent. Par contre, le style du composable parent est pas simple à adapter pour coller parfaitement au Buttton. Finalement, j'applique le style du 2e coin directement au bouton.

2024-04-13 14:43 UTC, AlexisPop commented on app/src/main/java/com/immobylette/appmobile/ui/shared/theme/Theme.kt
> +        LocalAppButtonWidth provides appButtonWidth,
Utilisé ici : 
![image](https://github.com/Immobylette/immobylette--app-mobile/assets/99278980/ff997546-6824-4cbf-a67d-9b9aa7826ade)

2024-04-14 20:58 UTC, patacoing approved these changes

2024-04-15 12:38 UTC, LfrPaul approved these changes

2024-04-17 06:53 UTC, OdakK approved these changes

2024-04-17 07:02 UTC, OdakK requested changes
Déplacer les constantes dans le component

2024-04-21 18:03 UTC, OdakK approved these changes

2024-04-21 21:21 UTC, merged