[ADD] signature composable
Immobylette/immobylette--app-mobile pull request #32
Opened 2024-05-21 20:42 UTC by patacoing

Avant signature : 
![image](https://github.com/Immobylette/immobylette--app-mobile/assets/78411800/f78a21fc-930c-4a6c-91c3-f24fb5dae8fc)

Après signature : 
![image](https://github.com/Immobylette/immobylette--app-mobile/assets/78411800/e087e922-e036-43f0-ae7d-222334cfb317)

Comme on avait pas définit l'affichage du switch après animation, j'ai juste échangé les couleurs, à vous de me dire si vous verriez de meilleurs possibilités

2024-05-21 20:42 UTC, patacoing commented
![](https://github.trello.services/images/mini-trello-icon.png) [Composant signature](https://trello.com/c/F5SJXi53/102-composant-signature)

2024-05-22 17:49 UTC, LfrPaul requested changes

2024-05-22 17:49 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/Signature.kt
> +    modifier: Modifier = Modifier
il faudrait pas un param "onChecked" à mettre sinon on pourra que signer visuellement avec le composant ?

2024-05-22 21:53 UTC, LfrPaul approved these changes

2024-05-28 17:04 UTC, merged