[ADD] Page de nouvel état
Immobylette/immobylette--app-mobile pull request #34
Opened 2024-05-28 16:16 UTC by LfrPaul

NewStepPage/NewStepNavigation/NewStepViewModel

Pour le bouton "Annuler"/La redirection quand on ajoute l'étape, il fallait savoir si on redirigé vers la liste des murs ou la liste des éléments, j'ai donc ajouté un attribut boolean isWall sur le StepState pour savoir où rediriger.

Quand on clique sur "Nouvel état", j'appelle une méthode pour reset le CurrentStep à partir d'un état comme ça on repart d'une étape à zéro

Pour la liste des photos du coup, si il n'y a qu'une seule photo, on ne peut pas la supprimer.

Aussi de mon côté, la requête d'ajout prennait pas mal de temps, du coup j'ai augmenté le timeout du client retrofit (si on est chaud on pourra essayer de faire un loader le temps que la requête s'execute mais c'était pas dans le ticket)

2024-05-28 16:16 UTC, LfrPaul commented
![](https://github.trello.services/images/mini-trello-icon.png) [Page nouvel état](https://trello.com/c/GFfMtutD/107-page-nouvel-%C3%A9tat)

2024-05-28 20:04 UTC, patacoing requested changes

2024-05-28 20:04 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/room/elements/ElementsPage.kt
> -        if (elements.elements.isEmpty())
pourquoi l'avoir supprimé ? cela permet de ne pas refaire la requête si l'on a déjà récup les éléments

2024-05-28 20:04 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/element/newstep/NewStepViewModel.kt
> +            onStepAdded()
dans le cas où la requête est successful la fonction onStepAdded s'exécute 2 fois, c'est normal ?

2024-05-28 20:04 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/element/newstep/NewStepPage.kt
> +                            .border(
par défaut avec les colors que tu as fournis, la border se fait toute seule avec le focus sur l'input nan ?

2024-05-28 20:04 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/element/newstep/NewStepPage.kt
> +                        .background(Color.Red)
à enlever

2024-05-28 20:09 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/room/elements/ElementsPage.kt
> -        if (elements.elements.isEmpty())
si on vient de check un élément, c'était plus simple de refaire la requête pour réafficher la liste mise à jour avec l'élément check

2024-05-28 20:13 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/element/newstep/NewStepPage.kt
> +                            .border(
quand j'avais testé je sais pas pourquoi mais sans ça il n'y avait que la bordure du bas sur l'input (c'est pour ça que j'ai mis focusedContainerColor = Color.Transparent d'ailleurs, c'était pour cacher la bordure du bas)

2024-05-29 06:53 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/room/elements/ElementsPage.kt
> -        if (elements.elements.isEmpty())
bien vu

2024-05-29 06:54 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/element/newstep/NewStepPage.kt
> +                            .border(
okok

2024-05-29 06:54 UTC, patacoing approved these changes

2024-06-03 13:03 UTC, OdakK approved these changes

2024-06-03 16:46 UTC, merged