[ADD] signature page
Immobylette/immobylette--app-mobile pull request #43
Opened 2024-06-09 20:41 UTC by OdakK

2024-06-09 20:42 UTC, OdakK commented
![](https://github.trello.services/images/mini-trello-icon.png) [Pages de signature](https://trello.com/c/RWUyes9n/103-pages-de-signature)

2024-06-09 22:20 UTC, LfrPaul approved these changes

2024-06-10 19:52 UTC, patacoing requested changes

2024-06-10 19:52 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/MainActivity.kt
> +                        onNavigateToPropertySelected = navController::navigateToAgentSignature
Tu as oublié de l'enlever

2024-06-10 19:52 UTC, patacoing commented on .idea/misc.xml
supp

2024-06-10 19:52 UTC, patacoing commented on .idea/deploymentTargetSelector.xml
supp

2024-06-11 14:43 UTC, patacoing approved these changes

2024-06-11 14:50 UTC, merged