[ADD] force screen orientation to portrait
Immobylette/immobylette--app-mobile pull request #46
Opened 2024-06-13 20:37 UTC by patacoing

2024-06-13 20:38 UTC, patacoing commented
![](https://github.trello.services/images/mini-trello-icon.png) [BUG : Modal de photo qui disparaît lors de passage en paysage / portrait](https://trello.com/c/Z74IA2aE/137-bug-modal-de-photo-qui-dispara%C3%AEt-lors-de-passage-en-paysage-portrait)

2024-06-14 21:38 UTC, OdakK requested changes

2024-06-14 21:38 UTC, OdakK commented on app/src/main/java/com/immobylette/appmobile/element/camera/CameraPage.kt
> +//                .setCaptureMode(CAPTURE_MODE_MINIMIZE_LATENCY)
enlever ommentaires

2024-06-16 10:49 UTC, OdakK approved these changes

2024-06-16 14:38 UTC, AlexisPop approved these changes

2024-06-16 18:32 UTC, LfrPaul approved these changes

2024-06-16 20:17 UTC, merged