[ADD] Add toast service + toats on same state, picture added, error d…
Immobylette/immobylette--app-mobile pull request #47
Opened 2024-06-13 21:00 UTC by OdakK

…eclared

2024-06-13 21:00 UTC, OdakK commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter toasts d'informations](https://trello.com/c/t9pJRMdk/129-ajouter-toasts-dinformations)

2024-06-13 21:37 UTC, patacoing requested changes
Est-ce ça ne serait pas possible d'utiliser la même font que celle de l'app pour les toasts ? ça serait moins choquant je pense

2024-06-13 21:37 UTC, patacoing commented on app/build.gradle.kts
> +    implementation("com.github.wordemo:MotionToast:master")
utiliser la syntaxe comme pour les autres imports en modifiant le fichier .toml

2024-06-16 15:38 UTC, AlexisPop requested changes

2024-06-16 15:38 UTC, AlexisPop commented on app/src/main/java/com/immobylette/appmobile/element/newstep/NewStepPage.kt
> +                                message = toastPhotoAddedMessage,
C'est pas plutôt : toast_message_picture_deleted ? dans le message

2024-06-16 15:38 UTC, AlexisPop commented on app/src/main/res/values/strings.xml
> +    <string name="toast_message_picture_added">Photo ajouté !</string>
"Photo ajoutée", il manque un e

2024-06-16 15:38 UTC, AlexisPop commented on app/src/main/res/values/strings.xml
> +    <string name="toast_message_error_declared">Erreur déclaré !</string>
"Erreur déclarée", il manque un e

2024-06-16 18:43 UTC, LfrPaul requested changes

2024-06-16 18:43 UTC, LfrPaul commented on app/src/main/res/values/strings.xml
> +    <string name="toast_title_success">Succés</string>
Succès c'est avec un accent grave

2024-06-16 20:18 UTC, patacoing approved these changes

2024-06-16 21:11 UTC, AlexisPop approved these changes

2024-06-17 06:23 UTC, merged