Feat/imb 128
Immobylette/immobylette--app-mobile pull request #50
Opened 2024-06-15 20:29 UTC by OdakK

2024-06-15 20:37 UTC, OdakK commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter toast pour les erreurs de requête API](https://trello.com/c/W2eZ8xsJ/128-ajouter-toast-pour-les-erreurs-de-requ%C3%AAte-api)

2024-06-16 15:48 UTC, AlexisPop approved these changes

2024-06-16 20:22 UTC, patacoing requested changes

2024-06-16 20:22 UTC, patacoing commented on .idea/deploymentTargetSelector.xml
supp le fichier

2024-06-16 20:22 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/toasts/ToastService.kt
> +    private const val toastErrorMessage = "Erreur survenue avec le serveur !"
utiliser le strings.xml

2024-06-16 20:53 UTC, OdakK commented on app/src/main/java/com/immobylette/appmobile/toasts/ToastService.kt
> +    private const val toastErrorMessage = "Erreur survenue avec le serveur !"
peut pas, stringRessource est seulement utilisable dans une activity

2024-06-17 06:19 UTC, merged