[ADD] PropertyCard Component
Immobylette/immobylette--app-mobile pull request #6
Opened 2024-04-23 17:12 UTC by LfrPaul

Ajout du composant PropertyCard

in_progress = false, et quand on clique dessus : 
![pas_in_progress](https://github.com/Immobylette/immobylette--app-mobile/assets/78427088/40eeba2f-efd4-4aff-9c67-0182825e44c3)

in_progress = true : 
![in_progress](https://github.com/Immobylette/immobylette--app-mobile/assets/78427088/7fa91b7a-0d6e-42bb-bf98-c97b99f5d3a1)

Aussi pour redéfinir les typo (headline, body, display etc), j'ai vu qu'il y avait un fichier dédié pour ça (Type.kt), donc j'ai deplacé dedans

 + J'ai aussi du changer le text du button pour mettre la couleur White

2024-04-23 19:07 UTC, patacoing requested changes

2024-04-23 19:07 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/PropertyCard.kt
> +    nb_rooms: Int,
Tous les params doivent être en camelCase

2024-04-23 19:07 UTC, patacoing commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/PropertyCard.kt
> +fun convertDistanceToString(distance: Float): String {
j'aurai plutôt mis ça dans un package util mais comme on va l'utiliser qu'une fois je sais pas trop

2024-04-23 19:08 UTC, LfrPaul commented
![](https://github.trello.services/images/mini-trello-icon.png) [Composant Property](https://trello.com/c/AhSxT8rB/56-composant-property)

2024-04-23 19:12 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/ui/shared/component/PropertyCard.kt
> +fun convertDistanceToString(distance: Float): String {
oui j'avais hésité à le laisser là ou pas mais on va l'utiliser que pour ce composant donc je me suis dis que ça pouvait rester dans ce fichier je sais pas trop non plus pour le coup

2024-04-23 19:24 UTC, patacoing approved these changes

2024-04-25 19:38 UTC, AlexisPop approved these changes

2024-04-25 20:06 UTC, merged