[ADD] loading page
Immobylette/immobylette--app-mobile pull request #9
Opened 2024-05-03 22:40 UTC by patacoing

2024-05-04 07:07 UTC, OdakK approved these changes

2024-05-07 09:03 UTC, patacoing commented
![](https://github.trello.services/images/mini-trello-icon.png) [Page de chargement](https://trello.com/c/0FEyp0ol/62-page-de-chargement)

2024-05-07 18:56 UTC, LfrPaul requested changes
Je sais pas si on le fait dans ce ticket en même temps ou si on le fera plus tard, mais pour la page des propriétés le "onNavigateToChangeAgent" il fait un navigateUp donc il va rediriger vers la page de loading non?

2024-05-07 18:56 UTC, LfrPaul commented on app/src/main/java/com/immobylette/appmobile/MainActivity.kt
> +                        onNavigateToAgentSelected = { navController.navigate("loading") }
ça serait pas mieux de créer dans LoadingNavigation une fonction navigateToLoadingPage et de l'utiliser ici ?

2024-05-07 20:54 UTC, LfrPaul approved these changes

2024-05-09 11:15 UTC, merged